org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.java.installations.fromEnv=JAVA_HOME_21_X64,JAVA_HOME_21_ARM64,JAVA_HOME_25_X64,JAVA_HOME_25_ARM64
org.gradle.parallel=true
org.gradle.warning.mode=all
kotlin.code.style=official
kotlin.incremental=true
