package io.github.kingsword09.kwebshell.bridge.codegen

import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json
import java.nio.file.Files
import java.nio.file.Path

public data class BridgeGeneratedSources(
    public val kotlin: String,
    public val typescript: String,
    public val browserJavascript: String,
)

public class BridgeGenerator public constructor() {
    public fun generate(schemaText: String): BridgeGeneratedSources {
        val schema = try {
            SCHEMA_JSON.decodeFromString<BridgeSchema>(schemaText)
        } catch (error: SerializationException) {
            throw IllegalArgumentException("The bridge schema is invalid: ${error.message}", error)
        }
        validate(schema)
        return BridgeGeneratedSources(
            kotlin = generateKotlin(schema),
            typescript = generateTypescript(schema),
            browserJavascript = generateBrowserJavascript(schema),
        )
    }

    public fun generate(schema: Path, outputDirectory: Path): List<Path> {
        val sources = generate(Files.readString(schema))
        Files.createDirectories(outputDirectory)
        val outputs = listOf(
            outputDirectory.resolve("${schemaBaseName(schema)}Bridge.kt") to sources.kotlin,
            outputDirectory.resolve("${schemaBaseName(schema)}Bridge.ts") to sources.typescript,
            outputDirectory.resolve("${schemaBaseName(schema)}Bridge.js") to sources.browserJavascript,
        )
        outputs.forEach { (path, content) -> Files.writeString(path, content) }
        return outputs.map { it.first }
    }

    private fun validate(schema: BridgeSchema) {
        require(schema.version == 1) { "Only bridge schema version 1 is supported." }
        require(TYPE_NAME.matches(schema.namespace)) { "The bridge namespace is invalid." }
        require(schema.namespace !in JAVASCRIPT_GLOBAL_NAMES) {
            "The bridge namespace collides with a JavaScript global."
        }
        require(PACKAGE_NAME.matches(schema.kotlinPackage)) { "The Kotlin package is invalid." }
        require(schema.kotlinPackage.split('.').none { it in KOTLIN_KEYWORDS }) {
            "The Kotlin package contains a reserved keyword."
        }
        require(schema.types.isNotEmpty()) { "The bridge schema must declare at least one type." }
        require(schema.methods.isNotEmpty()) { "The bridge schema must declare at least one method." }
        requireUnique(schema.types.map { it.name }, "type")
        requireUnique(schema.methods.map { it.name }, "method")
        val generatedTypeNames = setOf(
            "${schema.namespace}Handler",
            "${schema.namespace}Dispatcher",
            "${schema.namespace}Client",
            "KWebBridgeCallOptions",
            "KWebBridgeError",
        )
        val typeNames = schema.types.mapTo(mutableSetOf()) { type ->
            require(TYPE_NAME.matches(type.name)) { "Invalid bridge type name '${type.name}'." }
            require(type.name !in KOTLIN_TYPE_NAMES && type.name !in generatedTypeNames) {
                "Bridge type name '${type.name}' collides with a generated or Kotlin type."
            }
            require(type.fields.isNotEmpty()) { "Bridge type '${type.name}' has no fields." }
            requireUnique(type.fields.map { it.name }, "field in ${type.name}")
            type.fields.forEach { field ->
                require(FIELD_NAME.matches(field.name)) { "Invalid bridge field name '${field.name}'." }
                require(field.name !in KOTLIN_KEYWORDS) {
                    "Bridge field name '${type.name}.${field.name}' is a Kotlin keyword."
                }
            }
            type.name
        }
        schema.types.forEach { type ->
            type.fields.forEach { field ->
                require(field.type in PRIMITIVES || field.type in typeNames) {
                    "Bridge field '${type.name}.${field.name}' has unknown type '${field.type}'."
                }
            }
        }
        schema.methods.forEach { method ->
            require(METHOD_NAME.matches(method.name)) { "Invalid bridge method name '${method.name}'." }
            require(method.name !in KOTLIN_KEYWORDS) {
                "Bridge method name '${method.name}' is a Kotlin keyword."
            }
            require(method.request in typeNames) { "Unknown request type '${method.request}'." }
            require(method.response in typeNames) { "Unknown response type '${method.response}'." }
        }
    }

    private fun generateKotlin(schema: BridgeSchema): String = buildString {
        appendLine("// Generated by KWebShell bridge codegen. Do not edit.")
        appendLine("package ${schema.kotlinPackage}")
        appendLine()
        appendLine("import io.github.kingsword09.kwebshell.bridge.KWebBridgeDispatcher")
        appendLine("import io.github.kingsword09.kwebshell.bridge.KWebBridgeException")
        appendLine("import io.github.kingsword09.kwebshell.bridge.KWebBridgeProtocol")
        appendLine("import kotlinx.serialization.Serializable")
        appendLine("import kotlinx.serialization.decodeFromString")
        appendLine("import kotlinx.serialization.encodeToString")
        appendLine()
        schema.types.forEach { type ->
            appendLine("@Serializable")
            appendLine("public data class ${type.name}(")
            type.fields.forEach { field ->
                appendLine("    public val ${field.name}: ${kotlinType(field)},")
            }
            appendLine(")")
            appendLine()
        }
        appendLine("public interface ${schema.namespace}Handler {")
        schema.methods.forEach { method ->
            appendLine("    public suspend fun ${method.name}(request: ${method.request}): ${method.response}")
        }
        appendLine("}")
        appendLine()
        appendLine("public class ${schema.namespace}Dispatcher(")
        appendLine("    private val handler: ${schema.namespace}Handler,")
        appendLine(") : KWebBridgeDispatcher {")
        appendLine("    override suspend fun dispatch(requestJson: String): String {")
        appendLine("        val request = KWebBridgeProtocol.decodeRequest(requestJson)")
        appendLine("        return when (request.method) {")
        schema.methods.forEach { method ->
            appendLine("            \"${method.name}\" -> KWebBridgeProtocol.json.encodeToString(")
            appendLine("                handler.${method.name}(")
            appendLine("                    KWebBridgeProtocol.json.decodeFromString<${method.request}>(request.payload.toString()),")
            appendLine("                ),")
            appendLine("            )")
        }
        appendLine("            else -> throw KWebBridgeException(")
        appendLine("                code = \"bridge.method.unknown\",")
        appendLine("                message = \"Unknown bridge method '${'$'}{request.method}'.\",")
        appendLine("            )")
        appendLine("        }")
        appendLine("    }")
        appendLine("}")
    }

    private fun generateTypescript(schema: BridgeSchema): String = buildString {
        appendLine("// Generated by KWebShell bridge codegen. Do not edit.")
        schema.types.forEach { type ->
            appendLine("export interface ${type.name} {")
            type.fields.forEach { field ->
                appendLine("  ${field.name}: ${typescriptType(field)};")
            }
            appendLine("}")
            appendLine()
        }
        appendLine("export interface KWebBridgeCallOptions {")
        appendLine("  readonly signal?: AbortSignal;")
        appendLine("  readonly timeoutMs?: number;")
        appendLine("}")
        appendLine()
        appendLine("export class KWebBridgeError extends Error {")
        appendLine("  public constructor(public readonly code: string, message: string) {")
        appendLine("    super(message);")
        appendLine("    this.name = \"KWebBridgeError\";")
        appendLine("  }")
        appendLine("}")
        appendLine()
        appendLine("export interface ${schema.namespace}Client {")
        schema.methods.forEach { method ->
            appendLine("  ${method.name}(request: ${method.request}, options?: KWebBridgeCallOptions): Promise<${method.response}>;")
        }
        appendLine("}")
        appendLine()
        appendLine("declare global {")
        appendLine("  interface Window {")
        appendLine("    __kwebBridgeQuery(options: {")
        appendLine("      request: string;")
        appendLine("      persistent: false;")
        appendLine("      onSuccess(response: string): void;")
        appendLine("      onFailure(errorCode: number, errorMessage: string): void;")
        appendLine("    }): number;")
        appendLine("    __kwebBridgeCancel(requestId: number): void;")
        appendLine("  }")
        appendLine("}")
        appendLine()
        appendLine("${typescriptRuntime(schema)}")
    }

    private fun generateBrowserJavascript(schema: BridgeSchema): String = buildString {
        appendLine("// Generated by KWebShell bridge codegen. Do not edit.")
        appendLine("(() => {")
        appendLine("  \"use strict\";")
        appendLine("  class KWebBridgeError extends Error {")
        appendLine("    constructor(code, message) {")
        appendLine("      super(message);")
        appendLine("      this.name = \"KWebBridgeError\";")
        appendLine("      this.code = code;")
        appendLine("    }")
        appendLine("  }")
        appendLine("  ${javascriptInvokeFunction().prependIndent("  ").trimStart()}")
        appendLine("  const createClient = () => Object.freeze({")
        schema.methods.forEach { method ->
            appendLine("    ${method.name}: (request, options) => invoke(\"${method.name}\", request, options),")
        }
        appendLine("  });")
        appendLine("  Object.defineProperty(globalThis, \"${schema.namespace}\", {")
        appendLine("    configurable: false,")
        appendLine("    enumerable: false,")
        appendLine("    writable: false,")
        appendLine("    value: Object.freeze({ createClient, KWebBridgeError }),")
        appendLine("  });")
        appendLine("})();")
    }

    private fun typescriptRuntime(schema: BridgeSchema): String = buildString {
        appendLine("function invoke<T>(method: string, payload: unknown, options: KWebBridgeCallOptions = {}): Promise<T> {")
        appendLine("  return new Promise<T>((resolve, reject) => {")
        appendLine("    if (!Number.isSafeInteger(options.timeoutMs ?? 30000) || (options.timeoutMs ?? 30000) <= 0 || (options.timeoutMs ?? 30000) > 2147483647) {")
        appendLine("      reject(new KWebBridgeError(\"bridge.timeout.invalid\", \"timeoutMs must be an integer from 1 through 2147483647.\"));")
        appendLine("      return;")
        appendLine("    }")
        appendLine("    if (options.signal?.aborted) {")
        appendLine("      reject(new KWebBridgeError(\"bridge.call.cancelled\", \"The bridge call was cancelled.\"));")
        appendLine("      return;")
        appendLine("    }")
        appendLine("    let settled = false;")
        appendLine("    let queryId = 0;")
        appendLine("    const finish = (operation: () => void): void => {")
        appendLine("      if (settled) return;")
        appendLine("      settled = true;")
        appendLine("      clearTimeout(timer);")
        appendLine("      options.signal?.removeEventListener(\"abort\", cancel);")
        appendLine("      operation();")
        appendLine("    };")
        appendLine("    const cancel = (): void => finish(() => {")
        appendLine("      if (queryId !== 0) window.__kwebBridgeCancel(queryId);")
        appendLine("      reject(new KWebBridgeError(\"bridge.call.cancelled\", \"The bridge call was cancelled.\"));")
        appendLine("    });")
        appendLine("    const timer = setTimeout(() => finish(() => {")
        appendLine("      if (queryId !== 0) window.__kwebBridgeCancel(queryId);")
        appendLine("      reject(new KWebBridgeError(\"bridge.call.timeout\", \"The bridge call timed out.\"));")
        appendLine("    }), options.timeoutMs ?? 30000);")
        appendLine("    options.signal?.addEventListener(\"abort\", cancel, { once: true });")
        appendLine("    if (options.signal?.aborted) {")
        appendLine("      cancel();")
        appendLine("      return;")
        appendLine("    }")
        appendLine("    try {")
        appendLine("      queryId = window.__kwebBridgeQuery({")
        appendLine("      request: JSON.stringify({ version: 1, method, payload }),")
        appendLine("      persistent: false,")
        appendLine("        onSuccess: response => finish(() => {")
        appendLine("          try { resolve(JSON.parse(response) as T); }")
        appendLine("          catch { reject(new KWebBridgeError(\"bridge.response.invalid-json\", \"The bridge response is not valid JSON.\")); }")
        appendLine("        }),")
        appendLine("        onFailure: (_errorCode, errorMessage) => finish(() => {")
        appendLine("        let failure: { code?: string; message?: string } = {};")
        appendLine("        try { failure = JSON.parse(errorMessage); } catch { failure = {}; }")
        appendLine("        reject(new KWebBridgeError(failure.code ?? \"bridge.transport.failed\", failure.message ?? errorMessage));")
        appendLine("        }),")
        appendLine("      });")
        appendLine("      if (settled) window.__kwebBridgeCancel(queryId);")
        appendLine("    } catch (error) {")
        appendLine("      finish(() => reject(new KWebBridgeError(\"bridge.transport.failed\", error instanceof Error ? error.message : String(error))));")
        appendLine("    }")
        appendLine("  });")
        appendLine("}")
        appendLine()
        appendLine("export function create${schema.namespace}Client(): ${schema.namespace}Client {")
        appendLine("  return Object.freeze({")
        schema.methods.forEach { method ->
            appendLine(
                "    ${method.name}: (request: ${method.request}, options?: KWebBridgeCallOptions) => " +
                    "invoke<${method.response}>(\"${method.name}\", request, options),",
            )
        }
        appendLine("  });")
        appendLine("}")
    }.trimEnd()

    private fun javascriptInvokeFunction(): String = """
        function invoke(method, payload, options = {}) {
          return new Promise((resolve, reject) => {
            const timeoutMs = options.timeoutMs ?? 30000;
            if (!Number.isSafeInteger(timeoutMs) || timeoutMs <= 0 || timeoutMs > 2147483647) {
              reject(new KWebBridgeError("bridge.timeout.invalid", "timeoutMs must be an integer from 1 through 2147483647."));
              return;
            }
            if (options.signal?.aborted) {
              reject(new KWebBridgeError("bridge.call.cancelled", "The bridge call was cancelled."));
              return;
            }
            let settled = false;
            let queryId = 0;
            const finish = operation => {
              if (settled) return;
              settled = true;
              clearTimeout(timer);
              options.signal?.removeEventListener("abort", cancel);
              operation();
            };
            const cancel = () => finish(() => {
              if (queryId !== 0) globalThis.__kwebBridgeCancel(queryId);
              reject(new KWebBridgeError("bridge.call.cancelled", "The bridge call was cancelled."));
            });
            const timer = setTimeout(() => finish(() => {
              if (queryId !== 0) globalThis.__kwebBridgeCancel(queryId);
              reject(new KWebBridgeError("bridge.call.timeout", "The bridge call timed out."));
            }), timeoutMs);
            options.signal?.addEventListener("abort", cancel, { once: true });
            if (options.signal?.aborted) {
              cancel();
              return;
            }
            try {
              queryId = globalThis.__kwebBridgeQuery({
                request: JSON.stringify({ version: 1, method, payload }),
                persistent: false,
                onSuccess: response => finish(() => {
                  try { resolve(JSON.parse(response)); }
                  catch { reject(new KWebBridgeError("bridge.response.invalid-json", "The bridge response is not valid JSON.")); }
                }),
                onFailure: (_errorCode, errorMessage) => finish(() => {
                  let failure = {};
                  try { failure = JSON.parse(errorMessage); } catch { failure = {}; }
                  reject(new KWebBridgeError(failure.code ?? "bridge.transport.failed", failure.message ?? errorMessage));
                }),
              });
              if (settled) globalThis.__kwebBridgeCancel(queryId);
            } catch (error) {
              finish(() => reject(new KWebBridgeError("bridge.transport.failed", error instanceof Error ? error.message : String(error))));
            }
          });
        }
    """.trimIndent()

    private fun kotlinType(field: BridgeField): String {
        val base = KOTLIN_TYPES[field.type] ?: field.type
        val value = if (field.isList) "List<$base>" else base
        return if (field.nullable) "$value?" else value
    }

    private fun typescriptType(field: BridgeField): String {
        val base = TYPESCRIPT_TYPES[field.type] ?: field.type
        val value = if (field.isList) "readonly $base[]" else base
        return if (field.nullable) "$value | null" else value
    }

    private fun requireUnique(values: List<String>, description: String) {
        require(values.size == values.toSet().size) { "Duplicate $description names are not allowed." }
    }

    private fun schemaBaseName(path: Path): String =
        path.fileName.toString().substringBeforeLast('.').split('-', '_').joinToString("") {
            it.replaceFirstChar { character -> character.uppercaseChar() }
        }

    private companion object {
        val SCHEMA_JSON: Json = Json { ignoreUnknownKeys = false }
        val TYPE_NAME = Regex("[A-Z][A-Za-z0-9]{0,63}")
        val FIELD_NAME = Regex("[a-z][A-Za-z0-9]{0,63}")
        val METHOD_NAME = FIELD_NAME
        val PACKAGE_NAME = Regex("[a-z][a-z0-9]*(\\.[a-z][a-z0-9]*)+")
        val PRIMITIVES = setOf("string", "int32", "double", "boolean")
        val KOTLIN_TYPES = mapOf(
            "string" to "String",
            "int32" to "Int",
            "double" to "Double",
            "boolean" to "Boolean",
        )
        val TYPESCRIPT_TYPES = mapOf(
            "string" to "string",
            "int32" to "number",
            "double" to "number",
            "boolean" to "boolean",
        )
        val KOTLIN_TYPE_NAMES = KOTLIN_TYPES.values.toSet() + setOf(
            "List",
            "Serializable",
            "KWebBridgeDispatcher",
            "KWebBridgeException",
            "KWebBridgeProtocol",
        )
        val KOTLIN_KEYWORDS = setOf(
            "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if",
            "in", "interface", "is", "null", "object", "package", "return", "super", "this",
            "throw", "true", "try", "typealias", "typeof", "val", "var", "when", "while",
            "by", "catch", "constructor", "delegate", "dynamic", "field", "file", "finally",
            "get", "import", "init", "param", "property", "receiver", "set", "setparam", "value",
            "where", "actual", "abstract", "annotation", "companion", "const", "crossinline",
            "data", "enum", "expect", "external", "final", "infix", "inline", "inner", "internal",
            "lateinit", "noinline", "open", "operator", "out", "override", "private", "protected",
            "public", "reified", "sealed", "suspend", "tailrec", "vararg",
        )
        val JAVASCRIPT_GLOBAL_NAMES = setOf(
            "AbortController", "AbortSignal", "Array", "ArrayBuffer", "BigInt", "Boolean",
            "DataView", "Date", "Error", "EvalError", "FinalizationRegistry", "Function",
            "JSON", "Map", "Math", "Number", "Object", "Promise", "Proxy", "RangeError",
            "ReferenceError", "Reflect", "RegExp", "Set", "String", "Symbol", "SyntaxError",
            "TypeError", "URIError", "Uint8Array", "WeakMap", "WeakRef", "WeakSet", "Window",
            "Document", "Event", "Node", "URL", "WebSocket", "XMLHttpRequest",
        )
    }
}
