package io.github.kingsword09.kwebshell.electron.migration

import java.nio.file.Files
import java.nio.file.Path

public data class KWebElectronPreloadSources(
    public val typescript: String,
    public val declarations: String,
    public val javascript: String,
    public val checklist: String,
)

public class KWebElectronPreloadGenerator public constructor() {
    public fun generate(manifest: KWebElectronManifest): KWebElectronPreloadSources {
        val blockers = KWebElectronManifestValidator.blockingReasons(manifest)
        if (blockers.isNotEmpty()) throw KWebElectronMigrationException(KWebElectronMigrationErrorCode.MAPPING_UNRESOLVED, "The manifest contains unresolved migration declarations.", mapOf("reasons" to blockers.joinToString(",")))
        manifest.preloadMethods.forEach { method ->
            if (method.status != KWebElectronMappingStatus.ADAPTER ||
                method.adapter !in setOf(
                    KWebElectronAdapterKind.APP_PATHS_GET_PATH,
                    KWebElectronAdapterKind.FILES_OPERATION,
                    KWebElectronAdapterKind.CLIPBOARD_OPERATION,
                )
            ) {
                throw KWebElectronMigrationException(
                    code = KWebElectronMigrationErrorCode.MAPPING_UNRESOLVED,
                    details = mapOf("method" to method.name, "status" to method.status.name),
                    message = "The preload generator only emits complete published adapters.",
                )
            }
        }
        val methods = manifest.preloadMethods.sortedBy { it.name }
        val streams = manifest.streams.sortedBy { it.name }
        return KWebElectronPreloadSources(
            typescript = generateTypeScript(manifest, methods, streams),
            declarations = generateDeclarations(manifest, methods, streams),
            javascript = generateJavaScript(manifest, methods, streams),
            checklist = generateHostChecklist(manifest, methods, streams),
        )
    }

    public fun generate(manifest: KWebElectronManifest, outputDirectory: Path): List<Path> {
        val sources = generate(manifest)
        Files.createDirectories(outputDirectory)
        val outputs = listOf(
            outputDirectory.resolve("KWebElectronPreload.ts") to sources.typescript,
            outputDirectory.resolve("KWebElectronPreload.d.ts") to sources.declarations,
            outputDirectory.resolve("KWebElectronPreload.js") to sources.javascript,
            outputDirectory.resolve("KWebElectronHostChecklist.md") to sources.checklist,
        )
        outputs.forEach { (path, content) -> Files.writeString(path, content) }
        return outputs.map { it.first }
    }

    private fun generateHostChecklist(
        manifest: KWebElectronManifest,
        methods: List<KWebElectronPreloadMethod>,
        streams: List<KWebElectronStream>,
    ): String = buildString {
        appendLine("# KWebShell Migration Host Checklist: ${manifest.applicationId}")
        appendLine()
        appendLine("Generated by KWebShell Electron migration codegen. Deterministic across all platforms.")
        appendLine()
        appendLine("Renderer origin: `${manifest.rendererOrigin}`; profile: `${manifest.rendererProfile}`.")
        appendLine()
        appendLine("## 1. Required KMP Native Services")
        if (manifest.requiredServices.isEmpty()) {
            appendLine("- (None)")
        } else {
            manifest.requiredServices.sortedBy { it.id }.forEach {
                appendLine("- [ ] Install `${it.id}` (version `${it.version}`)")
            }
        }
        appendLine()
        appendLine("## 2. Window & Hierarchy Definitions")
        if (manifest.windows.isEmpty()) {
            appendLine("- [ ] No window declared")
        } else {
            manifest.windows.sortedBy { it.id }.forEach {
                val modalInfo = if (it.isModal) " (modal, parent: ${it.parentWindowId})" else ""
                val mainInfo = if (it.isMainWindow) " [Main]" else ""
                appendLine("- [ ] Window `${it.id}`: \"${it.title}\"$mainInfo (Profile: `${it.profile}`)$modalInfo")
                val fullscreenMode = when {
                    it.kiosk -> "KIOSK"
                    it.fullscreen -> "FULLSCREEN"
                    else -> "WINDOWED"
                }
                appendLine("  - [ ] Register immutable parent/modality and call `setFullscreen($fullscreenMode)` from host code.")
                appendLine("  - [ ] Apply typed capabilities: closable=${it.closable}, movable=${it.movable}, minimizable=${it.minimizable}, maximizable=${it.maximizable}, resizable=${it.resizable}, alwaysOnTop=${it.alwaysOnTop}.")
                it.bounds?.let { bounds ->
                    appendLine("  - [ ] Apply bounded `setBounds(${bounds.x}, ${bounds.y}, ${bounds.width}, ${bounds.height})` after registration.")
                }
            }
        }
        appendLine()
        appendLine("## 3. Profiles")
        if (manifest.profiles.isEmpty()) {
            appendLine("- [ ] No profile declared")
        } else {
            manifest.profiles.sortedBy { it.id }.forEach {
                val pers = if (it.isPersistent) "persistent" else "in-memory"
                appendLine("- [ ] Profile `${it.id}` ($pers, storage: `${it.storagePath ?: "in-memory"}`)")
            }
        }
        appendLine()
        appendLine("## 4. Preload Methods & Streams")
        methods.forEach { method ->
            appendLine("- [ ] Preload method `${method.name}` -> Channel `${method.channel}` (Status: `${method.status}`)")
        }
        streams.forEach { stream ->
            appendLine("- [ ] Stream `${stream.name}` -> Method `${stream.method}` (Capacity: `${stream.capacity}`, Status: `${stream.status}`)")
        }
        appendLine()
        appendLine("## 5. Node & Native Dependencies")
        if (manifest.nodeDependencies.isEmpty()) {
            appendLine("- (None)")
        } else {
            manifest.nodeDependencies.sortedBy { it.name }.forEach { dep ->
                val repl = dep.replacementServiceId?.let { " -> Replacement: `$it`" } ?: ""
                appendLine("- [ ] `${dep.name}` (${dep.kind}, Status: `${dep.status}`)$repl")
            }
        }
    }.trimEnd() + "\n"

    private fun generateTypeScript(
        manifest: KWebElectronManifest,
        methods: List<KWebElectronPreloadMethod>,
        streams: List<KWebElectronStream>,
    ): String = buildString {
        val filesMethods = methods.filter { it.adapter == KWebElectronAdapterKind.FILES_OPERATION }
        val filesStreams = streams.filter { it.adapter == KWebElectronAdapterKind.FILES_WATCH_DIRECTORY }
        val clipboardMethods = methods.filter { it.adapter == KWebElectronAdapterKind.CLIPBOARD_OPERATION }
        val applicationStreams = streams.filter { it.adapter == KWebElectronAdapterKind.NAMED_APPLICATION_STREAM }
        appendLine("// Generated by KWebShell Electron migration codegen. Do not edit.")
        appendLine("export type ElectronPathName = ${pathTypeUnion()};")
        appendFilesTypes(manifest, filesMethods, filesStreams)
        appendClipboardTypes(clipboardMethods)
        appendLine()
        appendLine("export interface KWebBridgeCallOptions {")
        appendLine("  readonly signal?: AbortSignal;")
        appendLine("  readonly timeoutMs?: number;")
        appendLine("}")
        appendLine()
        appendLine("export interface ${apiTypeName(manifest)} {")
        methods.forEach { method ->
            appendLine("  ${method.name}(${method.parameterName}: ${method.parameterType}, options?: KWebBridgeCallOptions): ${method.returnType};")
        }
        streams.forEach { stream ->
            appendLine("  ${stream.name}(request: ${stream.requestType}, options?: KWebElectronStreamOptions): KWebElectronStream<${stream.chunkType}>;")
        }
        appendLine("}")
        appendStreamTypes(streams)
        appendLine()
        appendLine("export class KWebElectronMigrationError extends Error {")
        appendLine("  public constructor(public readonly code: string, message: string) {")
        appendLine("    super(message);")
        appendLine("    this.name = \"KWebElectronMigrationError\";")
        appendLine("  }")
        appendLine("}")
        appendLine()
        appendLine("const pathKinds: Readonly<Record<ElectronPathName, string>> = Object.freeze({")
        electronPathKinds().forEach { (name, kind) -> appendLine("  ${name}: \"${kind}\",") }
        appendLine("});")
        appendLine()
        appendLine("export function install${manifest.rendererGlobal.replaceFirstChar { it.uppercaseChar() }}Preload(): void {")
        val appPathMethods = methods.filter { it.adapter == KWebElectronAdapterKind.APP_PATHS_GET_PATH }
        if (appPathMethods.isNotEmpty()) {
            appendLine("  const bridge = window.KWebAppPathsBridge;")
            appendLine("  if (!bridge || typeof bridge.createClient !== \"function\") {")
            appendLine("    throw new KWebElectronMigrationError(\"migration.bridge.missing\", \"KWebAppPathsBridge is required by this migration facade.\");")
            appendLine("  }")
            appendLine("  const client = bridge.createClient();")
        }
        if (filesMethods.isNotEmpty() || filesStreams.isNotEmpty()) {
            appendLine("  const filesBridge = window.FilesBridge;")
            appendLine("  if (!filesBridge || typeof filesBridge.createClient !== \"function\") {")
            appendLine("    throw new KWebElectronMigrationError(\"migration.files-bridge.missing\", \"FilesBridge is required by this migration facade.\");")
            appendLine("  }")
            appendLine("  const filesClient = filesBridge.createClient();")
        }
        if (clipboardMethods.isNotEmpty()) {
            appendLine("  const clipboardBridge = window.ClipboardBridge;")
            appendLine("  if (!clipboardBridge || typeof clipboardBridge.createClient !== \"function\") {")
            appendLine("    throw new KWebElectronMigrationError(\"migration.clipboard-bridge.missing\", \"ClipboardBridge is required by this migration facade.\");")
            appendLine("  }")
            appendLine("  const clipboardClient = clipboardBridge.createClient();")
        }
        if (applicationStreams.isNotEmpty()) {
            appendLine("  const streamBridge = window.KWebApplicationStreamsBridge;")
            appendLine("  if (!streamBridge || typeof streamBridge.createClient !== \"function\") throw new KWebElectronMigrationError(\"migration.stream-bridge.missing\", \"KWebApplicationStreamsBridge is required by this migration facade.\");")
            appendLine("  const bridgeStreams = streamBridge.createClient();")
        }
        appendLine("  const api: ${apiTypeName(manifest)} = Object.freeze({")
        methods.forEach { method ->
            when (method.adapter) {
                KWebElectronAdapterKind.APP_PATHS_GET_PATH -> {
                    appendLine("    ${method.name}: (name: ElectronPathName, options?: KWebBridgeCallOptions) => {")
                    appendLine("      const kind = pathKinds[name];")
                    appendLine("      if (typeof kind !== \"string\") {")
                    appendLine("        return Promise.reject(new KWebElectronMigrationError(\"migration.path-name.unsupported\", \"The Electron path name is not published by KWebShell.\"));")
                    appendLine("      }")
                    appendLine("      return client.resolve({ kind }, options).then(result => result.path);")
                    appendLine("    },")
                }
                KWebElectronAdapterKind.FILES_OPERATION -> {
                    appendLine("    ${method.name}: (request: ${method.parameterType}, options?: KWebBridgeCallOptions) => filesClient.${operationFor(manifest, method)}(request, options) as ${method.returnType},")
                }
                KWebElectronAdapterKind.CLIPBOARD_OPERATION -> {
                    appendLine("    ${method.name}: (request: ${method.parameterType}, options?: KWebBridgeCallOptions) => clipboardClient.${operationFor(manifest, method)}(request, options) as ${method.returnType},")
                }
                KWebElectronAdapterKind.FILES_WATCH_DIRECTORY -> error("files watch adapters are generated from manifest streams")
                KWebElectronAdapterKind.NAMED_APPLICATION_STREAM -> error("stream adapters are generated from manifest streams")
                null -> error("validated adapters cannot be null")
            }
        }
        streams.forEach { stream ->
            val receiver = if (stream.adapter == KWebElectronAdapterKind.FILES_WATCH_DIRECTORY) "filesClient" else "bridgeStreams"
            appendLine("    ${stream.name}: (request: ${stream.requestType}, options?: KWebElectronStreamOptions) => $receiver.open${stream.method.replaceFirstChar { it.uppercaseChar() }}(request, options),")
        }
        appendLine("  });")
        appendLine("  Object.defineProperty(window, \"${manifest.rendererGlobal}\", {")
        appendLine("    configurable: false,")
        appendLine("    enumerable: true,")
        appendLine("    writable: false,")
        appendLine("    value: api,")
        appendLine("  });")
        appendLine("}")
        appendLine()
        appendLine("declare global {")
        appendLine("  interface Window {")
        appendLine("    ${manifest.rendererGlobal}: ${apiTypeName(manifest)};")
        if (appPathMethods.isNotEmpty()) {
            appendLine("    KWebAppPathsBridge: {")
            appendLine("      createClient(): { resolve(request: { kind: string }, options?: KWebBridgeCallOptions): Promise<{ kind: string; path: string; source: string }> };")
            appendLine("    };")
        }
        if (filesMethods.isNotEmpty() || filesStreams.isNotEmpty()) {
            appendLine("    FilesBridge: {")
            val members = buildList {
                addAll(filesMethods.map { method ->
                    "${operationFor(manifest, method)}(request: ${method.parameterType}, options?: KWebBridgeCallOptions): ${method.returnType}"
                })
                addAll(filesStreams.map { stream ->
                    "open${stream.method.replaceFirstChar { it.uppercaseChar() }}(request: ${stream.requestType}, options?: KWebElectronStreamOptions): KWebElectronStream<${stream.chunkType}>"
                })
            }.joinToString("; ")
            appendLine("      createClient(): { $members };")
            appendLine("    };")
        }
        if (clipboardMethods.isNotEmpty()) {
            appendLine("    ClipboardBridge: {")
            val members = clipboardMethods.joinToString("; ") { method ->
                "${operationFor(manifest, method)}(request: ${method.parameterType}, options?: KWebBridgeCallOptions): ${method.returnType}"
            }
            appendLine("      createClient(): { ${members} };")
            appendLine("    };")
        }
        if (applicationStreams.isNotEmpty()) {
            appendLine("    KWebApplicationStreamsBridge: {")
            appendLine("      createClient(): { ${applicationStreams.joinToString("; ") { "open${it.method.replaceFirstChar { c -> c.uppercaseChar() }}(request: ${it.requestType}, options?: KWebElectronStreamOptions): KWebElectronStream<${it.chunkType}>" }} };")
            appendLine("    };")
        }
        appendLine("  }")
        appendLine("}")
        appendLine()
        appendLine("install${manifest.rendererGlobal.replaceFirstChar { it.uppercaseChar() }}Preload();")
        appendLine("export {};")
    }.trimEnd() + "\n"

    private fun generateDeclarations(
        manifest: KWebElectronManifest,
        methods: List<KWebElectronPreloadMethod>,
        streams: List<KWebElectronStream>,
    ): String = buildString {
        val filesMethods = methods.filter { it.adapter == KWebElectronAdapterKind.FILES_OPERATION }
        val filesStreams = streams.filter { it.adapter == KWebElectronAdapterKind.FILES_WATCH_DIRECTORY }
        val clipboardMethods = methods.filter { it.adapter == KWebElectronAdapterKind.CLIPBOARD_OPERATION }
        val applicationStreams = streams.filter { it.adapter == KWebElectronAdapterKind.NAMED_APPLICATION_STREAM }
        val appPathMethods = methods.filter { it.adapter == KWebElectronAdapterKind.APP_PATHS_GET_PATH }
        appendLine("// Generated by KWebShell Electron migration codegen. Do not edit.")
        appendLine("export type ElectronPathName = ${pathTypeUnion()};")
        appendFilesTypes(manifest, filesMethods, filesStreams)
        appendClipboardTypes(clipboardMethods)
        appendLine()
        appendLine("export interface KWebBridgeCallOptions {")
        appendLine("  readonly signal?: AbortSignal;")
        appendLine("  readonly timeoutMs?: number;")
        appendLine("}")
        appendLine()
        appendLine("export interface ${apiTypeName(manifest)} {")
        methods.forEach { method ->
            appendLine("  ${method.name}(${method.parameterName}: ${method.parameterType}, options?: KWebBridgeCallOptions): ${method.returnType};")
        }
        streams.forEach { stream ->
            appendLine("  ${stream.name}(request: ${stream.requestType}, options?: KWebElectronStreamOptions): KWebElectronStream<${stream.chunkType}>;")
        }
        appendLine("}")
        appendStreamTypes(streams)
        appendLine()
        appendLine("declare global {")
        appendLine("  interface Window {")
        appendLine("    ${manifest.rendererGlobal}: ${apiTypeName(manifest)};")
        if (appPathMethods.isNotEmpty()) {
            appendLine("    KWebAppPathsBridge: {")
            appendLine("      createClient(): { resolve(request: { kind: string }, options?: KWebBridgeCallOptions): Promise<{ kind: string; path: string; source: string }> };")
            appendLine("    };")
        }
        if (filesMethods.isNotEmpty() || filesStreams.isNotEmpty()) {
            appendLine("    FilesBridge: {")
            val members = buildList {
                addAll(filesMethods.map { method ->
                    "${operationFor(manifest, method)}(request: ${method.parameterType}, options?: KWebBridgeCallOptions): ${method.returnType}"
                })
                addAll(filesStreams.map { stream ->
                    "open${stream.method.replaceFirstChar { it.uppercaseChar() }}(request: ${stream.requestType}, options?: KWebElectronStreamOptions): KWebElectronStream<${stream.chunkType}>"
                })
            }.joinToString("; ")
            appendLine("      createClient(): { $members };")
            appendLine("    };")
        }
        if (clipboardMethods.isNotEmpty()) {
            appendLine("    ClipboardBridge: {")
            val members = clipboardMethods.joinToString("; ") { method ->
                "${operationFor(manifest, method)}(request: ${method.parameterType}, options?: KWebBridgeCallOptions): ${method.returnType}"
            }
            appendLine("      createClient(): { ${members} };")
            appendLine("    };")
        }
        if (applicationStreams.isNotEmpty()) {
            appendLine("    KWebApplicationStreamsBridge: {")
            appendLine("      createClient(): { ${applicationStreams.joinToString("; ") { "open${it.method.replaceFirstChar { c -> c.uppercaseChar() }}(request: ${it.requestType}, options?: KWebElectronStreamOptions): KWebElectronStream<${it.chunkType}>" }} };")
            appendLine("    };")
        }
        appendLine("  }")
        appendLine("}")
        appendLine("export {};")
    }.trimEnd() + "\n"

    private fun generateJavaScript(
        manifest: KWebElectronManifest,
        methods: List<KWebElectronPreloadMethod>,
        streams: List<KWebElectronStream>,
    ): String = buildString {
        val appPathMethods = methods.filter { it.adapter == KWebElectronAdapterKind.APP_PATHS_GET_PATH }
        val filesMethods = methods.filter { it.adapter == KWebElectronAdapterKind.FILES_OPERATION }
        val filesStreams = streams.filter { it.adapter == KWebElectronAdapterKind.FILES_WATCH_DIRECTORY }
        val clipboardMethods = methods.filter { it.adapter == KWebElectronAdapterKind.CLIPBOARD_OPERATION }
        val applicationStreams = streams.filter { it.adapter == KWebElectronAdapterKind.NAMED_APPLICATION_STREAM }
        appendLine("// Generated by KWebShell Electron migration codegen. Do not edit.")
        appendLine("(() => {")
        appendLine("  \"use strict\";")
        if (appPathMethods.isNotEmpty()) {
            appendLine("  const bridge = globalThis.KWebAppPathsBridge;")
            appendLine("  if (!bridge || typeof bridge.createClient !== \"function\") {")
            appendLine("    throw new Error(\"KWebAppPathsBridge is required by this migration facade.\");")
            appendLine("  }")
        }
        if (filesMethods.isNotEmpty() || filesStreams.isNotEmpty()) {
            appendLine("  const filesBridge = globalThis.FilesBridge;")
            appendLine("  if (!filesBridge || typeof filesBridge.createClient !== \"function\") {")
            appendLine("    throw new Error(\"FilesBridge is required by this migration facade.\");")
            appendLine("  }")
        }
        appendLine("  class KWebElectronMigrationError extends Error {")
        appendLine("    constructor(code, message) {")
        appendLine("      super(message);")
        appendLine("      this.name = \"KWebElectronMigrationError\";")
        appendLine("      this.code = code;")
        appendLine("    }")
        appendLine("  }")
        if (appPathMethods.isNotEmpty()) {
            appendLine("  const pathKinds = Object.freeze({")
            electronPathKinds().forEach { (name, kind) -> appendLine("    ${name}: \"${kind}\",") }
            appendLine("  });")
            appendLine("  const client = bridge.createClient();")
        }
        if (filesMethods.isNotEmpty() || filesStreams.isNotEmpty()) appendLine("  const filesClient = filesBridge.createClient();")
        if (clipboardMethods.isNotEmpty()) {
            appendLine("  const clipboardBridge = globalThis.ClipboardBridge;")
            appendLine("  if (!clipboardBridge || typeof clipboardBridge.createClient !== \"function\") throw new Error(\"ClipboardBridge is required by this migration facade.\");")
            appendLine("  const clipboardClient = clipboardBridge.createClient();")
        }
        if (applicationStreams.isNotEmpty()) {
            appendLine("  const streamBridge = globalThis.KWebApplicationStreamsBridge;")
            appendLine("  if (!streamBridge || typeof streamBridge.createClient !== \"function\") throw new Error(\"KWebApplicationStreamsBridge is required by this migration facade.\");")
            appendLine("  const bridgeStreams = streamBridge.createClient();")
        } else {
            appendLine("  const bridgeStreams = null;")
        }
        appendLine("  const api = Object.freeze({")
        methods.forEach { method ->
            when (method.adapter) {
                KWebElectronAdapterKind.APP_PATHS_GET_PATH -> {
                    appendLine("    ${method.name}: (name, options) => {")
                    appendLine("      const kind = pathKinds[name];")
                    appendLine("      if (typeof kind !== \"string\") {")
                    appendLine("        return Promise.reject(new KWebElectronMigrationError(\"migration.path-name.unsupported\", \"The Electron path name is not published by KWebShell.\"));")
                    appendLine("      }")
                    appendLine("      return client.resolve({ kind }, options).then(result => result.path);")
                    appendLine("    },")
                }
                KWebElectronAdapterKind.FILES_OPERATION -> {
                    appendLine("    ${method.name}: (request, options) => filesClient.${operationFor(manifest, method)}(request, options),")
                }
                KWebElectronAdapterKind.CLIPBOARD_OPERATION -> {
                    appendLine("    ${method.name}: (request, options) => clipboardClient.${operationFor(manifest, method)}(request, options),")
                }
                KWebElectronAdapterKind.FILES_WATCH_DIRECTORY -> error("files watch adapters are generated from manifest streams")
                KWebElectronAdapterKind.NAMED_APPLICATION_STREAM -> error("stream adapters are generated from manifest streams")
                null -> error("validated adapters cannot be null")
            }
        }
        streams.forEach { stream ->
            val receiver = if (stream.adapter == KWebElectronAdapterKind.FILES_WATCH_DIRECTORY) "filesClient" else "bridgeStreams"
            appendLine("    ${stream.name}: (request, options) => $receiver.open${stream.method.replaceFirstChar { it.uppercaseChar() }}(request, options),")
        }
        appendLine("  });")
        appendLine("  Object.defineProperty(globalThis, \"${manifest.rendererGlobal}\", {")
        appendLine("    configurable: false,")
        appendLine("    enumerable: true,")
        appendLine("    writable: false,")
        appendLine("    value: api,")
        appendLine("  });")
        appendLine("})();")
    }

    private fun StringBuilder.appendStreamTypes(streams: List<KWebElectronStream>) {
        if (streams.isEmpty()) return
        appendLine()
        streams.forEach { stream ->
            if (stream.adapter != KWebElectronAdapterKind.FILES_WATCH_DIRECTORY) {
                appendLine("export type ${stream.requestType} = Record<string, unknown>;")
                appendLine("export type ${stream.chunkType} = Record<string, unknown>;")
            }
        }
        appendLine("export interface KWebElectronStreamOptions {")
        appendLine("  readonly signal?: AbortSignal;")
        appendLine("}")
        appendLine("export interface KWebElectronStream<Chunk> extends AsyncIterable<Chunk> {")
        appendLine("  close(): void;")
        appendLine("}")
    }

    private fun StringBuilder.appendFilesTypes(
        manifest: KWebElectronManifest,
        methods: List<KWebElectronPreloadMethod>,
        streams: List<KWebElectronStream>,
    ) {
        val definitions = linkedMapOf<String, List<String>>()
        methods.forEach { method ->
            val operation = manifest.channels.single { it.name == method.channel }.operationId
                ?: error("A validated files adapter must declare an operation.")
            val requestFields = when (operation) {
                "open-workspace" -> listOf("workspaceId: string", "grants: readonly string[]")
                "open-file" -> listOf("parent: string", "name: string", "mode: string", "createIfMissing: boolean")
                "write-file" -> listOf("handle: string", "offset: string", "bytes: readonly number[]")
                "read-file" -> listOf("handle: string", "offset: string", "length: number")
                "list-directory" -> listOf("handle: string", "limit: number")
                "close-handle" -> listOf("handle: string")
                else -> emptyList()
            }
            if (requestFields.isNotEmpty()) definitions[method.parameterType] = requestFields
            val responseType = manifest.channels.single { it.name == method.channel }.responseType
            val responseFields = when (operation) {
                "open-workspace", "open-file" -> listOf("handle: string", "kind: string", "name: string", "grants: readonly string[]")
                "write-file" -> listOf("written: number")
                "read-file" -> listOf("bytes: readonly number[]", "eof: boolean")
                "list-directory" -> listOf("entries: readonly FilesDirectoryEntry[]", "truncated: boolean")
                "close-handle" -> listOf("closed: boolean")
                else -> emptyList()
            }
            if (responseFields.isNotEmpty()) definitions[responseType] = responseFields
        }
        if (methods.any { manifest.channels.single { channel -> channel.name == it.channel }.operationId == "list-directory" }) {
            definitions.putIfAbsent(
                "FilesDirectoryEntry",
                listOf("name: string", "kind: string", "sizeBytes: string | null", "lastModifiedEpochMillis: string"),
            )
        }
        streams.filter { it.adapter == KWebElectronAdapterKind.FILES_WATCH_DIRECTORY }.forEach { stream ->
            definitions[stream.requestType] = listOf("handle: string")
            definitions[stream.chunkType] = listOf("sequence: string", "kind: string", "name: string | null")
        }
        definitions.forEach { (type, fields) ->
            appendLine("export interface $type {")
            fields.forEach { field -> appendLine("  $field;") }
            appendLine("}")
        }
    }

    private fun StringBuilder.appendClipboardTypes(
        methods: List<KWebElectronPreloadMethod>,
    ) {
        if (methods.isEmpty()) return
        appendLine("export interface ClipboardPayloadDescriptor {")
        appendLine("  handle: string; format: string; encoding: string; sizeBytes: string;")
        appendLine("}")
        appendLine("export interface ClipboardReadRequest { selection: string; formats: readonly string[]; }")
        appendLine("export interface ClipboardReadResponse { sequence: string; available: readonly ClipboardPayloadDescriptor[]; }")
        appendLine("export interface ClipboardReadPayloadRequest { handle: string; offset: string; length: number; }")
        appendLine("export interface ClipboardReadPayloadResponse { bytes: readonly number[]; eof: boolean; }")
        appendLine("export interface ClipboardWriteItem { format: string; encoding: string; bytes: readonly number[]; }")
        appendLine("export interface ClipboardWriteRequest { selection: string; items: readonly ClipboardWriteItem[]; }")
        appendLine("export interface ClipboardClearRequest { selection: string; }")
        appendLine("export interface ClipboardWriteResponse { sequence: string; }")
        appendLine("export interface ClipboardClearResponse { sequence: string; }")
        appendLine("export interface ClipboardClosePayloadRequest { handle: string; }")
        appendLine("export interface ClipboardClosePayloadResponse { closed: boolean; }")
    }

    private fun apiTypeName(manifest: KWebElectronManifest): String =
        manifest.rendererGlobal.replaceFirstChar { it.uppercaseChar() } + "Api"

    private fun operationFor(
        manifest: KWebElectronManifest,
        method: KWebElectronPreloadMethod,
    ): String = manifest.channels.single { it.name == method.channel }.operationId
        ?.split('-')
        ?.mapIndexed { index, part -> if (index == 0) part else part.replaceFirstChar { it.uppercaseChar() } }
        ?.joinToString("")
        ?: error("A validated files adapter must declare an operation.")

    private fun pathTypeUnion(): String = electronPathKinds().keys.joinToString(" | ") { "\"$it\"" }

    private fun electronPathKinds(): LinkedHashMap<String, String> = linkedMapOf(
        "home" to "home",
        "appData" to "app-data",
        "userData" to "user-data",
        "sessionData" to "session-data",
        "temp" to "temp",
        "desktop" to "desktop",
        "documents" to "documents",
        "downloads" to "downloads",
        "music" to "music",
        "pictures" to "pictures",
        "videos" to "videos",
    )
}
