package io.github.kingsword09.kwebshell.electron.migration

import java.nio.file.Files
import java.nio.file.Path

public data class KWebElectronPreloadSources(
    public val typescript: String,
    public val declarations: String,
    public val javascript: String,
)

public class KWebElectronPreloadGenerator public constructor() {
    public fun generate(manifest: KWebElectronManifest): KWebElectronPreloadSources {
        KWebElectronManifestValidator.validate(manifest)
        manifest.preloadMethods.forEach { method ->
            if (method.status != KWebElectronMappingStatus.ADAPTER || method.adapter != KWebElectronAdapterKind.APP_PATHS_GET_PATH) {
                throw KWebElectronMigrationException(
                    code = KWebElectronMigrationErrorCode.MAPPING_UNRESOLVED,
                    details = mapOf("method" to method.name, "status" to method.status.name),
                    message = "The preload generator only emits complete published adapters.",
                )
            }
        }
        val methods = manifest.preloadMethods.sortedBy { it.name }
        return KWebElectronPreloadSources(
            typescript = generateTypeScript(manifest, methods),
            declarations = generateDeclarations(manifest, methods),
            javascript = generateJavaScript(manifest, methods),
        )
    }

    public fun generate(manifest: KWebElectronManifest, outputDirectory: Path): List<Path> {
        val sources = generate(manifest)
        Files.createDirectories(outputDirectory)
        val outputs = listOf(
            outputDirectory.resolve("KWebElectronPreload.ts") to sources.typescript,
            outputDirectory.resolve("KWebElectronPreload.d.ts") to sources.declarations,
            outputDirectory.resolve("KWebElectronPreload.js") to sources.javascript,
        )
        outputs.forEach { (path, content) -> Files.writeString(path, content) }
        return outputs.map { it.first }
    }

    private fun generateTypeScript(
        manifest: KWebElectronManifest,
        methods: List<KWebElectronPreloadMethod>,
    ): String = buildString {
        appendLine("// Generated by KWebShell Electron migration codegen. Do not edit.")
        appendLine("export type ElectronPathName = ${pathTypeUnion()};")
        appendLine()
        appendLine("export interface KWebBridgeCallOptions {")
        appendLine("  readonly signal?: AbortSignal;")
        appendLine("  readonly timeoutMs?: number;")
        appendLine("}")
        appendLine()
        appendLine("export interface ${apiTypeName(manifest)} {")
        methods.forEach { method ->
            appendLine("  ${method.name}(${method.parameterName}: ${method.parameterType}, options?: KWebBridgeCallOptions): ${method.returnType};")
        }
        appendLine("}")
        appendLine()
        appendLine("export class KWebElectronMigrationError extends Error {")
        appendLine("  public constructor(public readonly code: string, message: string) {")
        appendLine("    super(message);")
        appendLine("    this.name = \"KWebElectronMigrationError\";")
        appendLine("  }")
        appendLine("}")
        appendLine()
        appendLine("const pathKinds: Readonly<Record<ElectronPathName, string>> = Object.freeze({")
        electronPathKinds().forEach { (name, kind) -> appendLine("  ${name}: \"${kind}\",") }
        appendLine("});")
        appendLine()
        appendLine("export function install${manifest.rendererGlobal.replaceFirstChar { it.uppercaseChar() }}Preload(): void {")
        appendLine("  const bridge = window.KWebAppPathsBridge;")
        appendLine("  if (!bridge || typeof bridge.createClient !== \"function\") {")
        appendLine("    throw new KWebElectronMigrationError(\"migration.bridge.missing\", \"KWebAppPathsBridge is required by this migration facade.\");")
        appendLine("  }")
        appendLine("  const client = bridge.createClient();")
        appendLine("  const api: ${apiTypeName(manifest)} = Object.freeze({")
        methods.forEach { method ->
            appendLine("    ${method.name}: (name: ElectronPathName, options?: KWebBridgeCallOptions) => {")
            appendLine("      const kind = pathKinds[name];")
            appendLine("      if (typeof kind !== \"string\") {")
            appendLine("        return Promise.reject(new KWebElectronMigrationError(\"migration.path-name.unsupported\", \"The Electron path name is not published by KWebShell.\"));")
            appendLine("      }")
            appendLine("      return client.resolve({ kind }, options).then(result => result.path);")
            appendLine("    },")
        }
        appendLine("  });")
        appendLine("  Object.defineProperty(window, \"${manifest.rendererGlobal}\", {")
        appendLine("    configurable: false,")
        appendLine("    enumerable: true,")
        appendLine("    writable: false,")
        appendLine("    value: api,")
        appendLine("  });")
        appendLine("}")
        appendLine()
        appendLine("declare global {")
        appendLine("  interface Window {")
        appendLine("    ${manifest.rendererGlobal}: ${apiTypeName(manifest)};")
        appendLine("    KWebAppPathsBridge: {")
        appendLine("      createClient(): { resolve(request: { kind: string }, options?: KWebBridgeCallOptions): Promise<{ kind: string; path: string; source: string }> };")
        appendLine("    };")
        appendLine("  }")
        appendLine("}")
        appendLine()
        appendLine("install${manifest.rendererGlobal.replaceFirstChar { it.uppercaseChar() }}Preload();")
        appendLine("export {};")
    }.trimEnd() + "\n"

    private fun generateDeclarations(
        manifest: KWebElectronManifest,
        methods: List<KWebElectronPreloadMethod>,
    ): String = buildString {
        appendLine("// Generated by KWebShell Electron migration codegen. Do not edit.")
        appendLine("export type ElectronPathName = ${pathTypeUnion()};")
        appendLine()
        appendLine("export interface KWebBridgeCallOptions {")
        appendLine("  readonly signal?: AbortSignal;")
        appendLine("  readonly timeoutMs?: number;")
        appendLine("}")
        appendLine()
        appendLine("export interface ${apiTypeName(manifest)} {")
        methods.forEach { method ->
            appendLine("  ${method.name}(${method.parameterName}: ${method.parameterType}, options?: KWebBridgeCallOptions): ${method.returnType};")
        }
        appendLine("}")
        appendLine()
        appendLine("declare global {")
        appendLine("  interface Window {")
        appendLine("    ${manifest.rendererGlobal}: ${apiTypeName(manifest)};")
        appendLine("    KWebAppPathsBridge: {")
        appendLine("      createClient(): { resolve(request: { kind: string }, options?: KWebBridgeCallOptions): Promise<{ kind: string; path: string; source: string }> };")
        appendLine("    };")
        appendLine("  }")
        appendLine("}")
        appendLine("export {};")
    }.trimEnd() + "\n"

    private fun generateJavaScript(
        manifest: KWebElectronManifest,
        methods: List<KWebElectronPreloadMethod>,
    ): String = buildString {
        appendLine("// Generated by KWebShell Electron migration codegen. Do not edit.")
        appendLine("(() => {")
        appendLine("  \"use strict\";")
        appendLine("  const bridge = globalThis.KWebAppPathsBridge;")
        appendLine("  if (!bridge || typeof bridge.createClient !== \"function\") {")
        appendLine("    throw new Error(\"KWebAppPathsBridge is required by this migration facade.\");")
        appendLine("  }")
        appendLine("  class KWebElectronMigrationError extends Error {")
        appendLine("    constructor(code, message) {")
        appendLine("      super(message);")
        appendLine("      this.name = \"KWebElectronMigrationError\";")
        appendLine("      this.code = code;")
        appendLine("    }")
        appendLine("  }")
        appendLine("  const pathKinds = Object.freeze({")
        electronPathKinds().forEach { (name, kind) -> appendLine("    ${name}: \"${kind}\",") }
        appendLine("  });")
        appendLine("  const client = bridge.createClient();")
        appendLine("  const api = Object.freeze({")
        methods.forEach { method ->
            when (method.adapter) {
                KWebElectronAdapterKind.APP_PATHS_GET_PATH -> {
                    appendLine("    ${method.name}: (name, options) => {")
                    appendLine("      const kind = pathKinds[name];")
                    appendLine("      if (typeof kind !== \"string\") {")
                    appendLine("        return Promise.reject(new KWebElectronMigrationError(\"migration.path-name.unsupported\", \"The Electron path name is not published by KWebShell.\"));")
                    appendLine("      }")
                    appendLine("      return client.resolve({ kind }, options).then(result => result.path);")
                    appendLine("    },")
                }
                null -> error("validated adapters cannot be null")
            }
        }
        appendLine("  });")
        appendLine("  Object.defineProperty(globalThis, \"${manifest.rendererGlobal}\", {")
        appendLine("    configurable: false,")
        appendLine("    enumerable: true,")
        appendLine("    writable: false,")
        appendLine("    value: api,")
        appendLine("  });")
        appendLine("})();")
    }

    private fun apiTypeName(manifest: KWebElectronManifest): String =
        manifest.rendererGlobal.replaceFirstChar { it.uppercaseChar() } + "Api"

    private fun pathTypeUnion(): String = electronPathKinds().keys.joinToString(" | ") { "\"$it\"" }

    private fun electronPathKinds(): LinkedHashMap<String, String> = linkedMapOf(
        "home" to "home",
        "appData" to "app-data",
        "userData" to "user-data",
        "sessionData" to "session-data",
        "temp" to "temp",
        "desktop" to "desktop",
        "documents" to "documents",
        "downloads" to "downloads",
        "music" to "music",
        "pictures" to "pictures",
        "videos" to "videos",
    )
}
