// Generated by KWebShell Electron migration codegen. Do not edit.
export type ElectronPathName = "home" | "appData" | "userData" | "sessionData" | "temp" | "desktop" | "documents" | "downloads" | "music" | "pictures" | "videos";
export interface FilesCloseHandleRequest {
  handle: string;
}
export interface FilesCloseHandleResponse {
  closed: boolean;
}
export interface FilesListDirectoryRequest {
  handle: string;
  limit: number;
}
export interface FilesListDirectoryResponse {
  entries: readonly FilesDirectoryEntry[];
  truncated: boolean;
}
export interface FilesOpenFileRequest {
  parent: string;
  name: string;
  mode: string;
  createIfMissing: boolean;
}
export interface FilesHandleDescriptor {
  handle: string;
  kind: string;
  name: string;
  grants: readonly string[];
}
export interface FilesWorkspaceRequest {
  workspaceId: string;
  grants: readonly string[];
}
export interface FilesReadFileRequest {
  handle: string;
  offset: string;
  length: number;
}
export interface FilesReadFileResponse {
  bytes: readonly number[];
  eof: boolean;
}
export interface FilesWriteFileRequest {
  handle: string;
  offset: string;
  bytes: readonly number[];
}
export interface FilesWriteFileResponse {
  written: number;
}
export interface FilesDirectoryEntry {
  name: string;
  kind: string;
  sizeBytes: string | null;
  lastModifiedEpochMillis: string;
}
export interface FilesWatchRequest {
  handle: string;
}
export interface FilesWatchEvent {
  sequence: string;
  kind: string;
  name: string | null;
}
export interface ClipboardPayloadDescriptor {
  handle: string; format: string; encoding: string; sizeBytes: string;
}
export interface ClipboardReadRequest { selection: string; formats: readonly string[]; }
export interface ClipboardReadResponse { sequence: string; available: readonly ClipboardPayloadDescriptor[]; }
export interface ClipboardReadPayloadRequest { handle: string; offset: string; length: number; }
export interface ClipboardReadPayloadResponse { bytes: readonly number[]; eof: boolean; }
export interface ClipboardWriteItem { format: string; encoding: string; bytes: readonly number[]; }
export interface ClipboardWriteRequest { selection: string; items: readonly ClipboardWriteItem[]; }
export interface ClipboardClearRequest { selection: string; }
export interface ClipboardWriteResponse { sequence: string; }
export interface ClipboardClearResponse { sequence: string; }
export interface ClipboardClosePayloadRequest { handle: string; }
export interface ClipboardClosePayloadResponse { closed: boolean; }
export interface ShellExternalUriRequest { uri: string; }
export interface ShellResourceRequest { handle: string; }
export interface ShellActionResponse { action: string; outcome: string; resourceKind: string | null; }

export interface KWebBridgeCallOptions {
  readonly signal?: AbortSignal;
  readonly timeoutMs?: number;
}

export interface DesktopApi {
  clearClipboard(request: ClipboardClearRequest, options?: KWebBridgeCallOptions): Promise<ClipboardClearResponse>;
  closeClipboardPayload(request: ClipboardClosePayloadRequest, options?: KWebBridgeCallOptions): Promise<ClipboardClosePayloadResponse>;
  closeHandle(request: FilesCloseHandleRequest, options?: KWebBridgeCallOptions): Promise<FilesCloseHandleResponse>;
  getPath(name: ElectronPathName, options?: KWebBridgeCallOptions): Promise<string>;
  listDirectory(request: FilesListDirectoryRequest, options?: KWebBridgeCallOptions): Promise<FilesListDirectoryResponse>;
  openExternal(request: ShellExternalUriRequest, options?: KWebBridgeCallOptions): Promise<ShellActionResponse>;
  openFile(request: FilesOpenFileRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>;
  openResource(request: ShellResourceRequest, options?: KWebBridgeCallOptions): Promise<ShellActionResponse>;
  openWorkspace(request: FilesWorkspaceRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>;
  readClipboard(request: ClipboardReadRequest, options?: KWebBridgeCallOptions): Promise<ClipboardReadResponse>;
  readClipboardPayload(request: ClipboardReadPayloadRequest, options?: KWebBridgeCallOptions): Promise<ClipboardReadPayloadResponse>;
  readFile(request: FilesReadFileRequest, options?: KWebBridgeCallOptions): Promise<FilesReadFileResponse>;
  revealResource(request: ShellResourceRequest, options?: KWebBridgeCallOptions): Promise<ShellActionResponse>;
  trashResource(request: ShellResourceRequest, options?: KWebBridgeCallOptions): Promise<ShellActionResponse>;
  writeClipboard(request: ClipboardWriteRequest, options?: KWebBridgeCallOptions): Promise<ClipboardWriteResponse>;
  writeFile(request: FilesWriteFileRequest, options?: KWebBridgeCallOptions): Promise<FilesWriteFileResponse>;
  progress(request: DownloadRequest, options?: KWebElectronStreamOptions): KWebElectronStream<ProgressChunk>;
  watchDirectory(request: FilesWatchRequest, options?: KWebElectronStreamOptions): KWebElectronStream<FilesWatchEvent>;
}

export type DownloadRequest = Record<string, unknown>;
export type ProgressChunk = Record<string, unknown>;
export interface KWebElectronStreamOptions {
  readonly signal?: AbortSignal;
}
export interface KWebElectronStream<Chunk> extends AsyncIterable<Chunk> {
  close(): void;
}

export class KWebElectronMigrationError extends Error {
  public constructor(public readonly code: string, message: string) {
    super(message);
    this.name = "KWebElectronMigrationError";
  }
}

const pathKinds: Readonly<Record<ElectronPathName, string>> = Object.freeze({
  home: "home",
  appData: "app-data",
  userData: "user-data",
  sessionData: "session-data",
  temp: "temp",
  desktop: "desktop",
  documents: "documents",
  downloads: "downloads",
  music: "music",
  pictures: "pictures",
  videos: "videos",
});

export function installDesktopPreload(): void {
  const bridge = window.KWebAppPathsBridge;
  if (!bridge || typeof bridge.createClient !== "function") {
    throw new KWebElectronMigrationError("migration.bridge.missing", "KWebAppPathsBridge is required by this migration facade.");
  }
  const client = bridge.createClient();
  const filesBridge = window.FilesBridge;
  if (!filesBridge || typeof filesBridge.createClient !== "function") {
    throw new KWebElectronMigrationError("migration.files-bridge.missing", "FilesBridge is required by this migration facade.");
  }
  const filesClient = filesBridge.createClient();
  const clipboardBridge = window.ClipboardBridge;
  if (!clipboardBridge || typeof clipboardBridge.createClient !== "function") {
    throw new KWebElectronMigrationError("migration.clipboard-bridge.missing", "ClipboardBridge is required by this migration facade.");
  }
  const clipboardClient = clipboardBridge.createClient();
  const shellBridge = window.ShellBridge;
  if (!shellBridge || typeof shellBridge.createClient !== "function") {
    throw new KWebElectronMigrationError("migration.shell-bridge.missing", "ShellBridge is required by this migration facade.");
  }
  const shellClient = shellBridge.createClient();
  const streamBridge = window.KWebApplicationStreamsBridge;
  if (!streamBridge || typeof streamBridge.createClient !== "function") throw new KWebElectronMigrationError("migration.stream-bridge.missing", "KWebApplicationStreamsBridge is required by this migration facade.");
  const bridgeStreams = streamBridge.createClient();
  const api: DesktopApi = Object.freeze({
    clearClipboard: (request: ClipboardClearRequest, options?: KWebBridgeCallOptions) => clipboardClient.clear(request, options) as Promise<ClipboardClearResponse>,
    closeClipboardPayload: (request: ClipboardClosePayloadRequest, options?: KWebBridgeCallOptions) => clipboardClient.closePayload(request, options) as Promise<ClipboardClosePayloadResponse>,
    closeHandle: (request: FilesCloseHandleRequest, options?: KWebBridgeCallOptions) => filesClient.closeHandle(request, options) as Promise<FilesCloseHandleResponse>,
    getPath: (name: ElectronPathName, options?: KWebBridgeCallOptions) => {
      const kind = pathKinds[name];
      if (typeof kind !== "string") {
        return Promise.reject(new KWebElectronMigrationError("migration.path-name.unsupported", "The Electron path name is not published by KWebShell."));
      }
      return client.resolve({ kind }, options).then(result => result.path);
    },
    listDirectory: (request: FilesListDirectoryRequest, options?: KWebBridgeCallOptions) => filesClient.listDirectory(request, options) as Promise<FilesListDirectoryResponse>,
    openExternal: (request: ShellExternalUriRequest, options?: KWebBridgeCallOptions) => shellClient.openExternal(request, options) as Promise<ShellActionResponse>,
    openFile: (request: FilesOpenFileRequest, options?: KWebBridgeCallOptions) => filesClient.openFile(request, options) as Promise<FilesHandleDescriptor>,
    openResource: (request: ShellResourceRequest, options?: KWebBridgeCallOptions) => shellClient.openResource(request, options) as Promise<ShellActionResponse>,
    openWorkspace: (request: FilesWorkspaceRequest, options?: KWebBridgeCallOptions) => filesClient.openWorkspace(request, options) as Promise<FilesHandleDescriptor>,
    readClipboard: (request: ClipboardReadRequest, options?: KWebBridgeCallOptions) => clipboardClient.read(request, options) as Promise<ClipboardReadResponse>,
    readClipboardPayload: (request: ClipboardReadPayloadRequest, options?: KWebBridgeCallOptions) => clipboardClient.readPayload(request, options) as Promise<ClipboardReadPayloadResponse>,
    readFile: (request: FilesReadFileRequest, options?: KWebBridgeCallOptions) => filesClient.readFile(request, options) as Promise<FilesReadFileResponse>,
    revealResource: (request: ShellResourceRequest, options?: KWebBridgeCallOptions) => shellClient.revealResource(request, options) as Promise<ShellActionResponse>,
    trashResource: (request: ShellResourceRequest, options?: KWebBridgeCallOptions) => shellClient.trashResource(request, options) as Promise<ShellActionResponse>,
    writeClipboard: (request: ClipboardWriteRequest, options?: KWebBridgeCallOptions) => clipboardClient.write(request, options) as Promise<ClipboardWriteResponse>,
    writeFile: (request: FilesWriteFileRequest, options?: KWebBridgeCallOptions) => filesClient.writeFile(request, options) as Promise<FilesWriteFileResponse>,
    progress: (request: DownloadRequest, options?: KWebElectronStreamOptions) => bridgeStreams.openDownloadProgress(request, options),
    watchDirectory: (request: FilesWatchRequest, options?: KWebElectronStreamOptions) => filesClient.openWatchDirectory(request, options),
  });
  Object.defineProperty(window, "desktop", {
    configurable: false,
    enumerable: true,
    writable: false,
    value: api,
  });
}

declare global {
  interface Window {
    desktop: DesktopApi;
    KWebAppPathsBridge: {
      createClient(): { resolve(request: { kind: string }, options?: KWebBridgeCallOptions): Promise<{ kind: string; path: string; source: string }> };
    };
    FilesBridge: {
      createClient(): { closeHandle(request: FilesCloseHandleRequest, options?: KWebBridgeCallOptions): Promise<FilesCloseHandleResponse>; listDirectory(request: FilesListDirectoryRequest, options?: KWebBridgeCallOptions): Promise<FilesListDirectoryResponse>; openFile(request: FilesOpenFileRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>; openWorkspace(request: FilesWorkspaceRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>; readFile(request: FilesReadFileRequest, options?: KWebBridgeCallOptions): Promise<FilesReadFileResponse>; writeFile(request: FilesWriteFileRequest, options?: KWebBridgeCallOptions): Promise<FilesWriteFileResponse>; openWatchDirectory(request: FilesWatchRequest, options?: KWebElectronStreamOptions): KWebElectronStream<FilesWatchEvent> };
    };
    ClipboardBridge: {
      createClient(): { clear(request: ClipboardClearRequest, options?: KWebBridgeCallOptions): Promise<ClipboardClearResponse>; closePayload(request: ClipboardClosePayloadRequest, options?: KWebBridgeCallOptions): Promise<ClipboardClosePayloadResponse>; read(request: ClipboardReadRequest, options?: KWebBridgeCallOptions): Promise<ClipboardReadResponse>; readPayload(request: ClipboardReadPayloadRequest, options?: KWebBridgeCallOptions): Promise<ClipboardReadPayloadResponse>; write(request: ClipboardWriteRequest, options?: KWebBridgeCallOptions): Promise<ClipboardWriteResponse> };
    };
    ShellBridge: {
      createClient(): { openExternal(request: ShellExternalUriRequest, options?: KWebBridgeCallOptions): Promise<ShellActionResponse>; openResource(request: ShellResourceRequest, options?: KWebBridgeCallOptions): Promise<ShellActionResponse>; revealResource(request: ShellResourceRequest, options?: KWebBridgeCallOptions): Promise<ShellActionResponse>; trashResource(request: ShellResourceRequest, options?: KWebBridgeCallOptions): Promise<ShellActionResponse> };
    };
    KWebApplicationStreamsBridge: {
      createClient(): { openDownloadProgress(request: DownloadRequest, options?: KWebElectronStreamOptions): KWebElectronStream<ProgressChunk> };
    };
  }
}

installDesktopPreload();
export {};
