// Generated by KWebShell Electron migration codegen. Do not edit.
(() => {
  "use strict";
  const bridge = globalThis.KWebAppPathsBridge;
  if (!bridge || typeof bridge.createClient !== "function") {
    throw new Error("KWebAppPathsBridge is required by this migration facade.");
  }
  class KWebElectronMigrationError extends Error {
    constructor(code, message) {
      super(message);
      this.name = "KWebElectronMigrationError";
      this.code = code;
    }
  }
  const pathKinds = Object.freeze({
    home: "home",
    appData: "app-data",
    userData: "user-data",
    sessionData: "session-data",
    temp: "temp",
    desktop: "desktop",
    documents: "documents",
    downloads: "downloads",
    music: "music",
    pictures: "pictures",
    videos: "videos",
  });
  const client = bridge.createClient();
  const streamBridge = globalThis.KWebApplicationStreamsBridge;
  if (!streamBridge || typeof streamBridge.createClient !== "function") throw new Error("KWebApplicationStreamsBridge is required by this migration facade.");
  const bridgeStreams = streamBridge.createClient();
  const api = Object.freeze({
    getPath: (name, options) => {
      const kind = pathKinds[name];
      if (typeof kind !== "string") {
        return Promise.reject(new KWebElectronMigrationError("migration.path-name.unsupported", "The Electron path name is not published by KWebShell."));
      }
      return client.resolve({ kind }, options).then(result => result.path);
    },
    progress: (request, options) => bridgeStreams.openDownloadProgress(request, options),
  });
  Object.defineProperty(globalThis, "desktop", {
    configurable: false,
    enumerable: true,
    writable: false,
    value: api,
  });
})();
