// Generated by KWebShell Electron migration codegen. Do not edit.
(() => {
  "use strict";
  const bridge = globalThis.KWebAppPathsBridge;
  if (!bridge || typeof bridge.createClient !== "function") {
    throw new Error("KWebAppPathsBridge is required by this migration facade.");
  }
  const filesBridge = globalThis.FilesBridge;
  if (!filesBridge || typeof filesBridge.createClient !== "function") {
    throw new Error("FilesBridge is required by this migration facade.");
  }
  const shellBridge = globalThis.ShellBridge;
  if (!shellBridge || typeof shellBridge.createClient !== "function") throw new Error("ShellBridge is required by this migration facade.");
  const shellClient = shellBridge.createClient();
  const notificationsBridge = globalThis.NotificationsBridge;
  if (!notificationsBridge || typeof notificationsBridge.createClient !== "function") throw new Error("NotificationsBridge is required by this migration facade.");
  const notificationsClient = notificationsBridge.createClient();
  class KWebElectronMigrationError extends Error {
    constructor(code, message) {
      super(message);
      this.name = "KWebElectronMigrationError";
      this.code = code;
    }
  }
  const pathKinds = Object.freeze({
    home: "home",
    appData: "app-data",
    userData: "user-data",
    sessionData: "session-data",
    temp: "temp",
    desktop: "desktop",
    documents: "documents",
    downloads: "downloads",
    music: "music",
    pictures: "pictures",
    videos: "videos",
  });
  const client = bridge.createClient();
  const filesClient = filesBridge.createClient();
  const clipboardBridge = globalThis.ClipboardBridge;
  if (!clipboardBridge || typeof clipboardBridge.createClient !== "function") throw new Error("ClipboardBridge is required by this migration facade.");
  const clipboardClient = clipboardBridge.createClient();
  const streamBridge = globalThis.KWebApplicationStreamsBridge;
  if (!streamBridge || typeof streamBridge.createClient !== "function") throw new Error("KWebApplicationStreamsBridge is required by this migration facade.");
  const bridgeStreams = streamBridge.createClient();
  const api = Object.freeze({
    clearClipboard: (request, options) => clipboardClient.clear(request, options),
    closeClipboardPayload: (request, options) => clipboardClient.closePayload(request, options),
    closeHandle: (request, options) => filesClient.closeHandle(request, options),
    closeNotification: (request, options) => notificationsClient.close(request, options),
    getNotificationCapabilities: (request, options) => notificationsClient.capabilities(request, options),
    getPath: (name, options) => {
      const kind = pathKinds[name];
      if (typeof kind !== "string") {
        return Promise.reject(new KWebElectronMigrationError("migration.path-name.unsupported", "The Electron path name is not published by KWebShell."));
      }
      return client.resolve({ kind }, options).then(result => result.path);
    },
    listDirectory: (request, options) => filesClient.listDirectory(request, options),
    openExternal: (request, options) => shellClient.openExternal(request, options),
    openFile: (request, options) => filesClient.openFile(request, options),
    openResource: (request, options) => shellClient.openResource(request, options),
    openWorkspace: (request, options) => filesClient.openWorkspace(request, options),
    readClipboard: (request, options) => clipboardClient.read(request, options),
    readClipboardPayload: (request, options) => clipboardClient.readPayload(request, options),
    readFile: (request, options) => filesClient.readFile(request, options),
    revealResource: (request, options) => shellClient.revealResource(request, options),
    showNotification: (request, options) => notificationsClient.show(request, options),
    trashResource: (request, options) => shellClient.trashResource(request, options),
    writeClipboard: (request, options) => clipboardClient.write(request, options),
    writeFile: (request, options) => filesClient.writeFile(request, options),
    progress: (request, options) => bridgeStreams.openDownloadProgress(request, options),
    watchDirectory: (request, options) => filesClient.openWatchDirectory(request, options),
  });
  Object.defineProperty(globalThis, "desktop", {
    configurable: false,
    enumerable: true,
    writable: false,
    value: api,
  });
})();
