// Generated by KWebShell Electron migration codegen. Do not edit.
export type ElectronPathName = "home" | "appData" | "userData" | "sessionData" | "temp" | "desktop" | "documents" | "downloads" | "music" | "pictures" | "videos";

export interface KWebBridgeCallOptions {
  readonly signal?: AbortSignal;
  readonly timeoutMs?: number;
}

export interface DesktopApi {
  getPath(name: ElectronPathName, options?: KWebBridgeCallOptions): Promise<string>;
}

export type DownloadRequest = Record<string, unknown>;
export type ProgressChunk = Record<string, unknown>;
export interface KWebElectronStreamOptions {
  readonly signal?: AbortSignal;
}
export interface KWebElectronStream<Chunk> extends AsyncIterable<Chunk> {
  close(): void;
}

declare global {
  interface Window {
    desktop: DesktopApi;
    KWebAppPathsBridge: {
      createClient(): { resolve(request: { kind: string }, options?: KWebBridgeCallOptions): Promise<{ kind: string; path: string; source: string }> };
    };
    KWebApplicationStreamsBridge: {
      createClient(): { openDownloadProgress(request: DownloadRequest, options?: KWebElectronStreamOptions): KWebElectronStream<ProgressChunk> };
    };
  }
}
export {};
