// Generated by KWebShell Electron migration codegen. Do not edit.
export type ElectronPathName = "home" | "appData" | "userData" | "sessionData" | "temp" | "desktop" | "documents" | "downloads" | "music" | "pictures" | "videos";
export interface FilesCloseHandleRequest {
  handle: string;
}
export interface FilesCloseHandleResponse {
  closed: boolean;
}
export interface FilesListDirectoryRequest {
  handle: string;
  limit: number;
}
export interface FilesListDirectoryResponse {
  entries: readonly FilesDirectoryEntry[];
  truncated: boolean;
}
export interface FilesOpenFileRequest {
  parent: string;
  name: string;
  mode: string;
  createIfMissing: boolean;
}
export interface FilesHandleDescriptor {
  handle: string;
  kind: string;
  name: string;
  grants: readonly string[];
}
export interface FilesWorkspaceRequest {
  workspaceId: string;
  grants: readonly string[];
}
export interface FilesReadFileRequest {
  handle: string;
  offset: string;
  length: number;
}
export interface FilesReadFileResponse {
  bytes: readonly number[];
  eof: boolean;
}
export interface FilesWriteFileRequest {
  handle: string;
  offset: string;
  bytes: readonly number[];
}
export interface FilesWriteFileResponse {
  written: number;
}
export interface FilesDirectoryEntry {
  name: string;
  kind: string;
  sizeBytes: string | null;
  lastModifiedEpochMillis: string;
}
export interface FilesWatchRequest {
  handle: string;
}
export interface FilesWatchEvent {
  sequence: string;
  kind: string;
  name: string | null;
}

export interface KWebBridgeCallOptions {
  readonly signal?: AbortSignal;
  readonly timeoutMs?: number;
}

export interface DesktopApi {
  closeHandle(request: FilesCloseHandleRequest, options?: KWebBridgeCallOptions): Promise<FilesCloseHandleResponse>;
  getPath(name: ElectronPathName, options?: KWebBridgeCallOptions): Promise<string>;
  listDirectory(request: FilesListDirectoryRequest, options?: KWebBridgeCallOptions): Promise<FilesListDirectoryResponse>;
  openFile(request: FilesOpenFileRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>;
  openWorkspace(request: FilesWorkspaceRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>;
  readFile(request: FilesReadFileRequest, options?: KWebBridgeCallOptions): Promise<FilesReadFileResponse>;
  writeFile(request: FilesWriteFileRequest, options?: KWebBridgeCallOptions): Promise<FilesWriteFileResponse>;
  progress(request: DownloadRequest, options?: KWebElectronStreamOptions): KWebElectronStream<ProgressChunk>;
  watchDirectory(request: FilesWatchRequest, options?: KWebElectronStreamOptions): KWebElectronStream<FilesWatchEvent>;
}

export type DownloadRequest = Record<string, unknown>;
export type ProgressChunk = Record<string, unknown>;
export interface KWebElectronStreamOptions {
  readonly signal?: AbortSignal;
}
export interface KWebElectronStream<Chunk> extends AsyncIterable<Chunk> {
  close(): void;
}

declare global {
  interface Window {
    desktop: DesktopApi;
    KWebAppPathsBridge: {
      createClient(): { resolve(request: { kind: string }, options?: KWebBridgeCallOptions): Promise<{ kind: string; path: string; source: string }> };
    };
    FilesBridge: {
      createClient(): { closeHandle(request: FilesCloseHandleRequest, options?: KWebBridgeCallOptions): Promise<FilesCloseHandleResponse>; listDirectory(request: FilesListDirectoryRequest, options?: KWebBridgeCallOptions): Promise<FilesListDirectoryResponse>; openFile(request: FilesOpenFileRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>; openWorkspace(request: FilesWorkspaceRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>; readFile(request: FilesReadFileRequest, options?: KWebBridgeCallOptions): Promise<FilesReadFileResponse>; writeFile(request: FilesWriteFileRequest, options?: KWebBridgeCallOptions): Promise<FilesWriteFileResponse>; openWatchDirectory(request: FilesWatchRequest, options?: KWebElectronStreamOptions): KWebElectronStream<FilesWatchEvent> };
    };
    KWebApplicationStreamsBridge: {
      createClient(): { openDownloadProgress(request: DownloadRequest, options?: KWebElectronStreamOptions): KWebElectronStream<ProgressChunk> };
    };
  }
}
export {};
