// Generated by KWebShell Electron migration codegen. Do not edit.
export type ElectronPathName = "home" | "appData" | "userData" | "sessionData" | "temp" | "desktop" | "documents" | "downloads" | "music" | "pictures" | "videos";

export interface KWebBridgeCallOptions {
  readonly signal?: AbortSignal;
  readonly timeoutMs?: number;
}

export interface DesktopApi {
  getPath(name: ElectronPathName, options?: KWebBridgeCallOptions): Promise<string>;
}

export type DownloadRequest = Record<string, unknown>;
export type ProgressChunk = Record<string, unknown>;
export interface KWebElectronStreamOptions {
  readonly signal?: AbortSignal;
}
export interface KWebElectronStream<Chunk> extends AsyncIterable<Chunk> {
  close(): void;
}

export class KWebElectronMigrationError extends Error {
  public constructor(public readonly code: string, message: string) {
    super(message);
    this.name = "KWebElectronMigrationError";
  }
}

const pathKinds: Readonly<Record<ElectronPathName, string>> = Object.freeze({
  home: "home",
  appData: "app-data",
  userData: "user-data",
  sessionData: "session-data",
  temp: "temp",
  desktop: "desktop",
  documents: "documents",
  downloads: "downloads",
  music: "music",
  pictures: "pictures",
  videos: "videos",
});

export function installDesktopPreload(): void {
  const bridge = window.KWebAppPathsBridge;
  if (!bridge || typeof bridge.createClient !== "function") {
    throw new KWebElectronMigrationError("migration.bridge.missing", "KWebAppPathsBridge is required by this migration facade.");
  }
  const client = bridge.createClient();
  const streamBridge = window.KWebApplicationStreamsBridge;
  if (!streamBridge || typeof streamBridge.createClient !== "function") throw new KWebElectronMigrationError("migration.stream-bridge.missing", "KWebApplicationStreamsBridge is required by this migration facade.");
  const bridgeStreams = streamBridge.createClient();
  const api: DesktopApi = Object.freeze({
    getPath: (name: ElectronPathName, options?: KWebBridgeCallOptions) => {
      const kind = pathKinds[name];
      if (typeof kind !== "string") {
        return Promise.reject(new KWebElectronMigrationError("migration.path-name.unsupported", "The Electron path name is not published by KWebShell."));
      }
      return client.resolve({ kind }, options).then(result => result.path);
    },
    progress: (request: DownloadRequest, options?: KWebElectronStreamOptions) => bridgeStreams.openDownloadProgress(request, options),
  });
  Object.defineProperty(window, "desktop", {
    configurable: false,
    enumerable: true,
    writable: false,
    value: api,
  });
}

declare global {
  interface Window {
    desktop: DesktopApi;
    KWebAppPathsBridge: {
      createClient(): { resolve(request: { kind: string }, options?: KWebBridgeCallOptions): Promise<{ kind: string; path: string; source: string }> };
    };
    KWebApplicationStreamsBridge: {
      createClient(): { openDownloadProgress(request: DownloadRequest, options?: KWebElectronStreamOptions): KWebElectronStream<ProgressChunk> };
    };
  }
}

installDesktopPreload();
export {};
