// Generated by KWebShell Electron migration codegen. Do not edit.
export type ElectronPathName = "home" | "appData" | "userData" | "sessionData" | "temp" | "desktop" | "documents" | "downloads" | "music" | "pictures" | "videos";
export interface FilesCloseHandleRequest {
  handle: string;
}
export interface FilesCloseHandleResponse {
  closed: boolean;
}
export interface FilesListDirectoryRequest {
  handle: string;
  limit: number;
}
export interface FilesListDirectoryResponse {
  entries: readonly FilesDirectoryEntry[];
  truncated: boolean;
}
export interface FilesOpenFileRequest {
  parent: string;
  name: string;
  mode: string;
  createIfMissing: boolean;
}
export interface FilesHandleDescriptor {
  handle: string;
  kind: string;
  name: string;
  grants: readonly string[];
}
export interface FilesWorkspaceRequest {
  workspaceId: string;
  grants: readonly string[];
}
export interface FilesReadFileRequest {
  handle: string;
  offset: string;
  length: number;
}
export interface FilesReadFileResponse {
  bytes: readonly number[];
  eof: boolean;
}
export interface FilesWriteFileRequest {
  handle: string;
  offset: string;
  bytes: readonly number[];
}
export interface FilesWriteFileResponse {
  written: number;
}
export interface FilesDirectoryEntry {
  name: string;
  kind: string;
  sizeBytes: string | null;
  lastModifiedEpochMillis: string;
}
export interface FilesWatchRequest {
  handle: string;
}
export interface FilesWatchEvent {
  sequence: string;
  kind: string;
  name: string | null;
}

export interface KWebBridgeCallOptions {
  readonly signal?: AbortSignal;
  readonly timeoutMs?: number;
}

export interface DesktopApi {
  closeHandle(request: FilesCloseHandleRequest, options?: KWebBridgeCallOptions): Promise<FilesCloseHandleResponse>;
  getPath(name: ElectronPathName, options?: KWebBridgeCallOptions): Promise<string>;
  listDirectory(request: FilesListDirectoryRequest, options?: KWebBridgeCallOptions): Promise<FilesListDirectoryResponse>;
  openFile(request: FilesOpenFileRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>;
  openWorkspace(request: FilesWorkspaceRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>;
  readFile(request: FilesReadFileRequest, options?: KWebBridgeCallOptions): Promise<FilesReadFileResponse>;
  writeFile(request: FilesWriteFileRequest, options?: KWebBridgeCallOptions): Promise<FilesWriteFileResponse>;
  progress(request: DownloadRequest, options?: KWebElectronStreamOptions): KWebElectronStream<ProgressChunk>;
  watchDirectory(request: FilesWatchRequest, options?: KWebElectronStreamOptions): KWebElectronStream<FilesWatchEvent>;
}

export type DownloadRequest = Record<string, unknown>;
export type ProgressChunk = Record<string, unknown>;
export interface KWebElectronStreamOptions {
  readonly signal?: AbortSignal;
}
export interface KWebElectronStream<Chunk> extends AsyncIterable<Chunk> {
  close(): void;
}

export class KWebElectronMigrationError extends Error {
  public constructor(public readonly code: string, message: string) {
    super(message);
    this.name = "KWebElectronMigrationError";
  }
}

const pathKinds: Readonly<Record<ElectronPathName, string>> = Object.freeze({
  home: "home",
  appData: "app-data",
  userData: "user-data",
  sessionData: "session-data",
  temp: "temp",
  desktop: "desktop",
  documents: "documents",
  downloads: "downloads",
  music: "music",
  pictures: "pictures",
  videos: "videos",
});

export function installDesktopPreload(): void {
  const bridge = window.KWebAppPathsBridge;
  if (!bridge || typeof bridge.createClient !== "function") {
    throw new KWebElectronMigrationError("migration.bridge.missing", "KWebAppPathsBridge is required by this migration facade.");
  }
  const client = bridge.createClient();
  const filesBridge = window.FilesBridge;
  if (!filesBridge || typeof filesBridge.createClient !== "function") {
    throw new KWebElectronMigrationError("migration.files-bridge.missing", "FilesBridge is required by this migration facade.");
  }
  const filesClient = filesBridge.createClient();
  const streamBridge = window.KWebApplicationStreamsBridge;
  if (!streamBridge || typeof streamBridge.createClient !== "function") throw new KWebElectronMigrationError("migration.stream-bridge.missing", "KWebApplicationStreamsBridge is required by this migration facade.");
  const bridgeStreams = streamBridge.createClient();
  const api: DesktopApi = Object.freeze({
    closeHandle: (request: FilesCloseHandleRequest, options?: KWebBridgeCallOptions) => filesClient.closeHandle(request, options) as Promise<FilesCloseHandleResponse>,
    getPath: (name: ElectronPathName, options?: KWebBridgeCallOptions) => {
      const kind = pathKinds[name];
      if (typeof kind !== "string") {
        return Promise.reject(new KWebElectronMigrationError("migration.path-name.unsupported", "The Electron path name is not published by KWebShell."));
      }
      return client.resolve({ kind }, options).then(result => result.path);
    },
    listDirectory: (request: FilesListDirectoryRequest, options?: KWebBridgeCallOptions) => filesClient.listDirectory(request, options) as Promise<FilesListDirectoryResponse>,
    openFile: (request: FilesOpenFileRequest, options?: KWebBridgeCallOptions) => filesClient.openFile(request, options) as Promise<FilesHandleDescriptor>,
    openWorkspace: (request: FilesWorkspaceRequest, options?: KWebBridgeCallOptions) => filesClient.openWorkspace(request, options) as Promise<FilesHandleDescriptor>,
    readFile: (request: FilesReadFileRequest, options?: KWebBridgeCallOptions) => filesClient.readFile(request, options) as Promise<FilesReadFileResponse>,
    writeFile: (request: FilesWriteFileRequest, options?: KWebBridgeCallOptions) => filesClient.writeFile(request, options) as Promise<FilesWriteFileResponse>,
    progress: (request: DownloadRequest, options?: KWebElectronStreamOptions) => bridgeStreams.openDownloadProgress(request, options),
    watchDirectory: (request: FilesWatchRequest, options?: KWebElectronStreamOptions) => filesClient.openWatchDirectory(request, options),
  });
  Object.defineProperty(window, "desktop", {
    configurable: false,
    enumerable: true,
    writable: false,
    value: api,
  });
}

declare global {
  interface Window {
    desktop: DesktopApi;
    KWebAppPathsBridge: {
      createClient(): { resolve(request: { kind: string }, options?: KWebBridgeCallOptions): Promise<{ kind: string; path: string; source: string }> };
    };
    FilesBridge: {
      createClient(): { closeHandle(request: FilesCloseHandleRequest, options?: KWebBridgeCallOptions): Promise<FilesCloseHandleResponse>; listDirectory(request: FilesListDirectoryRequest, options?: KWebBridgeCallOptions): Promise<FilesListDirectoryResponse>; openFile(request: FilesOpenFileRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>; openWorkspace(request: FilesWorkspaceRequest, options?: KWebBridgeCallOptions): Promise<FilesHandleDescriptor>; readFile(request: FilesReadFileRequest, options?: KWebBridgeCallOptions): Promise<FilesReadFileResponse>; writeFile(request: FilesWriteFileRequest, options?: KWebBridgeCallOptions): Promise<FilesWriteFileResponse>; openWatchDirectory(request: FilesWatchRequest, options?: KWebElectronStreamOptions): KWebElectronStream<FilesWatchEvent> };
    };
    KWebApplicationStreamsBridge: {
      createClient(): { openDownloadProgress(request: DownloadRequest, options?: KWebElectronStreamOptions): KWebElectronStream<ProgressChunk> };
    };
  }
}

installDesktopPreload();
export {};
